name: 'Install MacPorts'
description: >-
  Install MacPorts on a Mac OS runner.
inputs:
  version:
    description: >-
      The MacPorts Version to install.
    required: true
    default: '2.8.0'

runs:
  using: 'composite'
  steps:
    - name: 'Install MacPorts'
      run: ${{ github.action_path }}/install_macports ${{ inputs.version }}
      shell: sh
    - name: 'Add MacPorts to PATH'
      run: >-
        printf '/opt/local/bin\n' >> $GITHUB_PATH
        printf '/opt/loca/sbin\n' >> $GITHUB_PATH
      shell: sh
