name: 'Install MacPorts'
description: >-
  Install MacPorts on a Mac OS runner.
inputs:
  version:
    description: >-
      The MacPorts Version to install.
    required: true
    default: '2.8.0'
  variants:
    description: >-
      Pathname of the variants configuration file to use.
      If the no file exists under this pathname, an information
      message is printed and the variants file installed by MacPorts
      is left untouched.

      See Also: variants.conf(5)
    required: true
    default: '.github/gha-install-macports/variants.conf'
  sources:
    description: >-
      Pathname of the sources configuration file to use.
      If the no file exists under this pathname, an information
      message is printed and the variants file installed by MacPorts
      is left untouched.

      See Also: sources.conf(5)
    required: true
    default: '.github/gha-install-macports/sources.conf'
  ports:
    description: >-
      Pathname of the ports configuration file to use.

      Each line in the file is a port specification for the port
      install action.

      If the no file exists under this pathname, an information
      message is printed and no supplementary port is installed.
    required: true
    default: '.github/gha-install-macports/ports.conf'
  prefix:
    description: >-
      Installation prefix. Currently the only supported value is '/opt/local'
    required: false
    default: '/opt/local'
outputs:
  version:
    value: ${{ steps.store-macports-outputs.outputs.version }}
    description: >-
      The MacPorts version installed.
  prefix:
    value: ${{ steps.store-macports-outputs.outputs.prefix }}
    description: >-
      The installation prefix for the MacPorts installation.
runs:
  using: 'composite'
  steps:
    - name: 'Validate Inputs'
      shell: sh
      run: |
        ${{ github.action_path }}/validate_prefix "${{ inputs.prefix }}"
    - name: 'Install MacPorts'
      shell: sh
      run: ${{ github.action_path }}/install_macports ${{ inputs.version }}
    - name: 'Write Configuration files'
      shell: sh
      run: |
        sudo ${{ github.action_path }}/write_configuration -S "${{ inputs.prefix }}/etc/gha-install-macports/version.conf" "${{ inputs.version }}"
        sudo ${{ github.action_path }}/write_configuration -P "${{ inputs.prefix }}/etc/gha-install-macports/variants.conf" "${{ inputs.variants }}"
        sudo ${{ github.action_path }}/write_configuration -P "${{ inputs.prefix }}/etc/gha-install-macports/sources.conf" "${{ inputs.sources }}"
        sudo ${{ github.action_path }}/write_configuration -P "${{ inputs.prefix }}/etc/gha-install-macports/ports.conf" "${{ inputs.ports }}"
        sudo ${{ github.action_path }}/write_configuration -S "${{ inputs.prefix }}/etc/gha-install-macports/prefix.conf" "${{ inputs.prefix }}"
    - name: 'Configure MacPorts'
      shell: sh
      run: |
        sudo ${{ github.action_path }}/configure_macports
    - name: 'Add MacPorts to PATH'
      shell: sh
      run: |
        printf '${{ inputs.prefix }}/bin\n' >> $GITHUB_PATH
        printf '${{ inputs.prefix }}/sbin\n' >> $GITHUB_PATH
    - name: 'Install Additional Ports'
      if: (inputs.ports != '')
      shell: sh
      run: |
        if [ -f "${{ inputs.ports }}" ]; then
          sudo xargs port install < "${{ inputs.ports }}"
        fi
    - name: 'Store MacPorts Output'
      id: store-macports-outputs
      shell: sh
      run: |-
        printf 'prefix=%s\n' "${{ inputs.prefix }}" >> $GITHUB_OUTPUT
        printf 'version=%s\n' "${{ inputs.version }}" >> $GITHUB_OUTPUT
