name: 'Continuous Integration'
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - v1
    tags-ignore:
      - v1.*

jobs:
  run-testsuite:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-12', 'macos-13', 'macos-14']
    runs-on: '${{ matrix.os }}'
    name: 'Run Testsuite'
    steps:
      - uses: actions/checkout@v4
      - name: 'Run testsuite'
        run: development/testsuite

  install-macports:
    strategy:
      matrix:
        os: ['macos-12', 'macos-13', 'macos-14']
        version: ['2.9.3']
        prefix: ['/opt/local']
    runs-on: '${{ matrix.os }}'
    name: 'Install MacPorts'
    needs: 'run-testsuite'
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: 'macports'
        with:
          parameters: 'testsuite/run-testsuite-on-${{ matrix.os }}.yaml'
      - name: 'Validate installed MacPorts version'
        run: >-
          test "$(port version)" = 'Version: ${{ matrix.version }}'
      - name: 'Validate transmitted MacPorts prefix'
        run: >-
          test "${{ steps.macports.outputs.prefix }}" = '${{ matrix.prefix }}'
      - name: 'Validate transmitted MacPorts version'
        run: >-
          test "${{ steps.macports.outputs.version }}" = '${{ matrix.version }}'
      - run: port version
