name: 'Run Testsuite'
on:
  - workflow_dispatch
  - push

jobs:
  run-testsuite-on-macos-11:
    runs-on: macos-11
    name: Install MacPorts 2.8.0 on MacOS 11
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: 'macports'
        with:
          variants: 'testsuite/run-testsuite-on-macos-11/variants.conf'
          ports: 'testsuite/run-testsuite-on-macos-11/ports.conf'
      - name: 'Print Configuration Files'
        run: >-
          sudo find ${{ steps.macports.outputs.prefix }}/etc/gha-install-macports
          -type f
          -exec awk 'FNR == 1 {printf("\n\nFilename: %s\n", FILENAME)} {print}' '{}' '+'          
      - name: 'Validate installed MacPorts version'
        run: >-
          test "$(port version)" = 'Version: 2.8.0'
      - name: 'Validate installed MacPorts prefix'
        run: >-
          test "${{ steps.macports.outputs.prefix }}" = '/opt/local'
      - name: 'Validate installed MacPorts version'
        run: >-
          test "${{ steps.macports.outputs.version }}" = '2.8.0'

  run-testsuite-on-macos-12:
    runs-on: macos-12
    name: Install MacPorts 2.8.0 on MacOS 12
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: port version
